### ISSUE TITLE
Use Symbols for path prop

### ISSUE THREAD

**Issue by bedeoverend** [SimplaElements/simpla-paths#2]
Right now we're just setting the `path` property on any element that has an `sid` / `gid` property. This is a risk if the user wants to use these attributes on elements that already have a `path` property that's used for something else. There's no standard HTML `path` property, but users could have a custom-element that adds it.

This could be resolved by using a [Symbol](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Symbol), rather than a String as the property. This would protect for unknown elements.

From a simpla element's perspective, to keep the regular `path` property on them, as well as getting the value from `simpla-paths`, it would have to import the Symbol used by `simpla-paths` (not much weight given tree-shaking), and pass the value set by paths to it's own path property. e.g.

```js
import { PathSymbol } from 'simpla-paths';

class SimplaText extends HTMLElement {
  set [ PathSymbol ](value) {
    this.path = value;
  }

  get [ PathSymbol ](value) {
    return this.path;
  }
}
```

A Symbol polyfill would also have to be bundled somewhere, as Symbols [aren't supported at all by IE](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Symbol#AutoCompatibilityTable), AFAIK the polyfill is relatively lightweight e.g. are used by SkateJS.

**Comment by madeleineostoja** [comment]
I don't really see the benefit of this, considering the extra weight and inconvenience for element authors. I definitely don't think we should do this unless/until there is a strong need for it from users.

**Comment by bedeoverend** [comment]
Hmm...I might close this until we know definitely how much of a pain it is. It's definitely dodgy just setting properties on unknown elements, but I'm happy to wait until someone actually runs into the problem, it's a relatively small change anyway, so even though it's breaking, it wouldn't be much work to update other elements.
